### PR TITLE
Combine readme and wiki onto centralized docs

### PR DESCRIPTION
**Pull request by louis-lau**
Following my suggestion in #202 I went ahead and combined the large readme and the wiki into a nice documentation page that's hopefully a bit less cluttered. Also created a page with third party projects by @rqelibari, me, and @ramiroaisen.

As you can only have 1 github pages site per repo I took the liberty to move the api docs to docs.wildduck.email/api

Currently up and running here:
https://louis-lau.github.io/wildduck

Let me know what you think! 😁

### CODE REVIEW

**Comment by andris9** [comment]
Looks great!

**Comment by louis-lau** [comment]
👍 

Don't forget the cname for docs.wildduck.email, and maybe a redirect on api.wildduck.email 😁

**Comment by rqelibari** [comment]
@louis-lau Great work, that looks awesome!

**Comment by louis-lau** [comment]
Thanks!

**Pull request merged**
