### PR TITLE
Added link to Project Pending

### PR DESCRIPTION
**Pull request by andris9**
Added link to Project Pending to 3rd party software docs.

### CODE REVIEW

**Comment by andris9** [comment]
@louis-lau how did you think the ordering of these projects should be organised? Does the "by commit date" mean that older projects go first?

**Comment by louis-lau** [comment]
Yeah that my intention, would get too tempting to put my own project on top otherwise 😁. But do whatever you want, maybe they should be sorted by relevance, though I find that hard to quantify.

**Comment by andris9** [comment]
Ok, it's totally fine. I was adding one of my own projects and did not want to give an advantage to it, better treat everyone equally on that side.

**Comment by louis-lau** [comment]
😁

**Comment by louis-lau** [comment]
I like the cat detective idea

**Pull request merged**
