### PR TITLE
Dockerize the repo

### PR DESCRIPTION
**Pull request by rakshith-ravi**
Worked on by @thebongy

### CODE REVIEW

**Comment by rqelibari** [comment]
Hi @rakshith-ravi,

thank you for your efforts to dockerize Wildduck.

Currently your approach is just a (dockerized) wrapper around the install scripts that does  does not integrate any sophisticated feature, that would make sense, when using a repository-integrated docker solution. @AddoSolutions already proposed a simple container like your's (see [here](https://github.com/nodemailer/wildduck/issues/71#issuecomment-385190084)) in issue #79.

There has been a great discussion over at issue #71 on what features a repository-integrated docker solution should offer. We, at Astzweig, took another approach at [astzweig/docker-wildduck](/astzweig/docker-wildduck), and are currently missing the resources to implement those additional features. Maybe you can use or repository as a base and try to develop solutions for the missing features.

**Comment by rakshith-ravi** [comment]
@rqelibari, our goal is to setup separate docker images for each parts of wildduck, while providing a docker-compose.yml file that acts as an example. This way, each part of wildduck can scale independently as a separate container. If these goals align with yours, we'd be happy to work on your image. That being said, we'd also prefer to have it integrated with this repo and built using travis to have a consistent version number across both the non-docker setup and the docker version. Does that sound like something you'd be willing to work on? If that sounds good to you, we'd be happy to contribute to your repo instead

**Comment by rqelibari** [comment]
@rakshith-ravi Thank you for the clarification. That sounds like a good approach in my opinion, as it produces many small containers and people can decide themselves, what components of the wildduck ecosystem they want to use (e.g. haraka as inbound SMTP or something else).
Tying the versioning of each container to the specific service makes sense, too, using this approach. In my opinion it is the only approach that can be included in the repository directly.

## Approach of Astzweig
The repo at [astzweig/docker-wildduck](/astzweig/docker-wildduck) on the other side is about providing a fully functional email server based on wildduck. In such a container tying the version to one single service is therefor not viable.

**Comment by rakshith-ravi** [comment]
Thank you for the feedback. Much appreciated.

As far as the PR goes, could you please help us review it? We're trying to understand if there are any issues in it so far or if we are even working on the right direction. I've tried reaching out to @andris9 (both here and on gitter), but I'm not able to get through to him. Could you please review this PR and let us know if it's fine?

**Comment by andris9** [comment]
@rakshith-ravi  @rqelibari I don't really have an opinion of how docker image should look like. The problem is that it can be composed in so many different ways and there's always someone who wants to do it some other way, this is why I haven't merged so far any of the dockerization PRs. If anyone has asked, I've pointed to the Astzweig repo.

If you can somehow figure out together the best way of how docker setup should look like, I'm willing to merge it to the repo.

**Comment by rakshith-ravi** [comment]
I personally think we should have multiple docker images for each service that wildduck offers, and bundle them all together in a compose file that can be used as an example (for someone who's just all about "show me the code to get it up and running"). This would also give the option of decoupling the services and scaling them up individually if required.

That being said, I think we can keep going on and on about the right way to do it, when in reality, not a lot of decisions make _that_ much of a difference. As long as it doesn't affect scalability and simplicity of use (which, if I'm not wrong, are some of the main goals of this project), we can go with any way of doing it. We propose the above to make things easier. We would really like some opinions from other people on the shortcomings of our approach and how we can improve this. If no one has any issues, I'd suggest we merge this and take a look at it later on when we face any issues with it

**Comment by rqelibari** [comment]
@andris9 That captures the situation quite well!

@rakshith-ravi Exactly. I think the idea to provide a docker container for each part of wildduck makes sense. It should be easy for users though, to use a specific container, e.g. users should be able to use ready-made containers from [Docker Hub](https://hub.docker.com) and run them without too much trouble.

### The configuration problem
Wildduck needs to know the address of the `mongo` server to run properly,  which can be configured at [db.toml](/nodemailer/wildduck/blob/master/config/dbs.toml#L2). So the user will most likely need to change this configuration option. To change that configuration option though, the user needs to have the whole source code of the [wildduck repository](/nodemailer/wildduck) to rebuild the entire container. A Docker Hub instance of the container would make not sense. Hence a runtime configuration seems to be a better approach. The [12 factor container](https://medium.com/notbinary/the-twelve-factor-container-8d1edc2a49d4) article of notbinary has a good explanation on that topic.

### The environment solution
I suggest, making the container configurable by environment variables. At least the most important configuration options (see the list over at [astzweig/docker-wildduck](/astzweig/docker-wildduck#environment-variables) for examples).

#### Cocof
At [astzweig/docker-wildduck](/astzweig/docker-wildduck) we developed a python package called `cocof` ([cocof at PyPi](https://pypi.org/project/cocof/)) to configure the container at runtime. E.g. to configure wildduck, you could run the followin line in a shell script:

```bash
cocof '/wildduck/config/default.toml' '[{"op": "add", "path": "/emailDomain", "value": "example.com"}]';
```
You can take a look at the script [_wildduck.sh](/astzweig/docker-wildduck/blob/master/scripts/_wildduck.sh) to see how we configure wildduck at runtime.

**Comment by rakshith-ravi** [comment]
How about mounting the db.toml file on an external volume and changing it's contents accordingly?

**Comment by louis-lau** [comment]
This is fine if you only have one server. In a multi server setup with docker swarm or kubernetes you don't want to store the config in volumes. It would make it harder to scale.

**Comment by rakshith-ravi** [comment]
Can't the volumes be shared across the containers?

But yeah, I do see your point. It's not the most scalable. But wouldn't the same issue be faced in the non-dockerized version of wildduck as well?

**Comment by louis-lau** [comment]
> Can't the volumes be shared across the containers?

Sure, but a volume is bound to the host the container is running on. This can change, and you need the config on all running hosts.

> But wouldn't the same issue be faced in the non-dockerized version of wildduck as well?

Yes! Which is why a dockerized version would be great :)

**Comment by rakshith-ravi** [comment]
> Yes! Which is why a dockerized version would be great :)  

Haha yeah point taken. 

So I was thinking that the config files can be shared across hosts using an NFS mount. Since they're not gonna be accessed often, the speed of access doesn't really matter. But other than that, it'll be very difficult to change the way that works without modifying the way wildduck loads config data. I'm not sure if @andris9 is willing to change that.

**Comment by louis-lau** [comment]
Andris doesn't have to do it, it could be a PR if you had the time. The problem I see with that is that environment variables have character restrictions, and their contents can only be a string.

You could get the environment variables and transform them to a toml/json/js config when starting the container.

**Comment by thebongy** [comment]
> This is fine if you only have one server. In a multi server setup with docker swarm or kubernetes you don't want to store the config in volumes. It would make it harder to scale. Environment variables are the way to go.

For docker swarms, instead of using a volume, docker has [`docker config`](https://docs.docker.com/engine/swarm/configs/), which basically shares configuration files across multiple nodes in the swarms. This lets you mount the config files, in this case `default.toml` across multiple nodes, just like you would mount a volume

For kubernetes, there is a similar solution with [`configmap`](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/)

I think for a use case involving swarms/kubernetes, these options are much easier to configure (and cleaner) rather than having to modify multiple environment variables, which would be hard to maintain as the configuration options change/new configuration options are introduced. This also lets us decouple configuration from the actual container, thus keeping the containers portable, which is one of the main principles of containerization

**Comment by louis-lau** [comment]
Damn, thanks @thebongy!

**Comment by rqelibari** [comment]
@thebongy Good point about the problem of keeping environment variables aligned with their corresponding configuration option. Still, talking from a UX position, I think there should be environment variables for the most important configuration options - options that will most probably need to be changed by every user -  like the FQDN.

### UX Reasoning
If probably everyone has to tell wildduck their servers FQDN than a simple environment variable is easier defined than using `docker config` to first define a configuration file, than finding out, where the correct path is and so on.

### The mysql container
If you take a look at the official [mysql container](https://hub.docker.com/_/mysql) you can see, that they take the same approach. Everyone is most probably going to set their own `mysql` root password, so despite of [`docker secrets`](https://docs.docker.com/engine/reference/commandline/secret/) they offer a environment variable to configure the `mysql` database that way, simply as a UX decision.

**Comment by thebongy** [comment]
@rqelibari I've had a look at the repo you mentioned [astzweig/docker-wildduck](https://github.com/astzweig/docker-wildduck), it provides a really nice way to setup common configuration options across Wildduck, zonmeta, and haraka, but the goal here is to setup a Dockerfile for wildduck as independent of other repos as possible.

I totally get the UX argument, but I don't think it is necessary to have a script in the Dockerfile to write env variables to the config files. There is another alternative to use [wild-config](https://github.com/nodemailer/wild-config) which already has a feature to pass configuration through command line options.

So I could provide a provision in the Dockerfile on this  PR to pass command line args to the RUN command as such:

```
ENV CMD_ARG
RUN node server.js ${CMD_ARGS}
```

and let's say a user wanted to configure the mongo and redis URL, he could pass them to docker run as env args, instead of having to mount the config file as volume or use `docker config`.
```
docker run -e CMD_ARGS="--dbs.mongo='mongo://mongo_host' --dbs.redis='redis://redis_host'" wildduck
```

This approach has the benefit of again, keeping the container image as independent of the configuration as possible, thus making it easier to maintain in the future.

I think along with some documentation on the wildduck README on how to use the `CMD_ARG` option to set common fields like the `FQDN` , this can work better, from a UX perspective. What do you think?

**Comment by rqelibari** [comment]
@thebongy That is a good idea using a wildcard environment variable to pass options to `wildduck` in combination with the documentation of the most important options in the README file.

Hence, in order to merge this PR we need two commits:

- [ ] 1. Change the Dockerfile as described by @thebongy.
- [ ] 2. Add a section in the README file that either describes the usage of `CMD_ARGS` or links to an article in the Wiki. In my opinion at least the following configuration options should be described:
  - Setting the FQDN of the server.
  - Setting the default domain name for which the email server shall receive emails.
  - Setting the domain name of the `redis` host.
  - Setting the connection link of the `mongo` host.

Everyone all right with that?

### Docker Hub
@andris9 In order for us to publish a Docker container of wildduck on Docker HUB, you will need to register on Docker HUB ([here](https://hub.docker.com)). Afterwards I can make you the owner of the `nodemailer` Organization, that I created on Docker Hub, so that you can link either your own account or a specific service account to Docker Hub ([Docker Hub service accounts](https://docs.docker.com/docker-hub/builds/#service-users-for-team-autobuilds)).

**Comment by andris9** [comment]
@rqelibari my docker hub username is andris9

**Comment by thebongy** [comment]
@rqelibari the Dockerfile now accepts the env variable `CMD_ARGS`. Have included a quick way to get the docker container running on the repo's `README.md`.

Additionally, I have created a wiki page @ (https://github.com/nodemailer/wildduck/wiki/Docker) with more detailed instructions to configure the container

**Comment by rqelibari** [comment]
@thebongy That is awesome, nice work!
@andris9 You can merge this PR now. Afterwards you need [to link](https://hub.docker.com/orgs/nodemailer/settings/linked-accounts) either your own github account with the nodemailer organization or create a "service" account, as described [here](https://docs.docker.com/docker-hub/builds/#service-users-for-team-autobuilds) and link that one, so that I can configure autobuild.

**Comment by andris9** [comment]
Looks great indeed!

**Comment by rakshith-ravi** [comment]
Is the docker image not published to docker hub?

**Comment by andris9** [comment]
@rakshith-ravi @rqelibari  I forgot to link Github account with Docker. Did this just now, so wildduck repo should be accessible from Docker Hub.

**Comment by rakshith-ravi** [comment]
Thank you @andris9. @rqelibari can we setup autobuilds with the correct tags please?

**Comment by rqelibari** [comment]
Docker Hub's autobuild is set up and the first build is finished: [https://hub.docker.com/r/nodemailer/wildduck](https://hub.docker.com/r/nodemailer/wildduck)

Every change on the `master` branch will trigger a new build of the `latest` container. Every new tag will trigger a new build of the container with the same tag.

**Comment by rakshith-ravi** [comment]
Awesome! Thank you @rqelibari! 

Is there any way we can trigger builds for existing tags as well?

**Comment by rqelibari** [comment]
> Is there any way we can trigger builds for existing tags as well?

@rakshith-ravi No, as the repository did not have a Dockerfile before.

**Comment by rakshith-ravi** [comment]
> > Is there any way we can trigger builds for existing tags as well?
> 
> @rakshith-ravi No, as the repository did not have a Dockerfile before.

@rqelibari it looks like the newer tags that were published aren't updating on docker hub either. Can you please see if something is configured wrong?

**Comment by rqelibari** [comment]
@rakshith-ravi You are right, thanks for noticing. I had missed a 'v' in the regular expression. Just reconfigured it.

Before:
Screen Shot 2020-04-06 at 21 08 55

After:
Screen Shot 2020-04-06 at 21 19 49

**Comment by rakshith-ravi** [comment]
Got it. Thanks

**Comment by rakshith-ravi** [comment]
Does this mean the tags will appear in docker hub?

https://hub.docker.com/r/nodemailer/wildduck/tags

I'm not able to see the tags yet. I'll check again tomorrow.

**Comment by rqelibari** [comment]
> Does this mean the tags will appear in docker hub?

@rakshith-ravi No, only new tags will appear in docker hub. So the next time andris tags a commit, docker hub should create a tagged build.

**Pull request merged**
